### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by vincent-dravert** [E-vence/SoftDeleteableListenerExtensionBundle#24] opened 2019-12-14 04:42 UTC

**Comment by jukuan** [comment] 2022-03-18 11:25
I can confirm that it does work fine on Symfony 5. It does not work well for Symfony 6 out-of-box. But it needs only small changes to be working: https://github.com/E-vence/SoftDeleteableListenerExtensionBundle/pull/32/files

**Comment by samdark** [comment] 2024-02-12 17:00
Should this one be closed?

**Comment by jukuan** [comment] 2024-02-12 20:05
Yes. I think, you can close that, because the pull-request above has been merged. And there is 2024, not 2019 :)

**Comment by samdark** [comment] 2024-02-12 20:18
I'm not repository owner.

**Comment by RubenHarms** [comment] 2024-02-13 09:13
Closed on request!

**Closed** 2024-02-13 09:13 UTC
